## dictionary

In [1]:
x = {'leo': 'shipeng', 'yvonne':'huan'}

In [3]:
print(type(x))


<class 'dict'>


In [29]:
for a, b in x.items():
    print(a)
    print(b)

leo
shipeng
yvonne
huan


In [21]:
for item in x.values():
    print(item)

shipeng
huan


In [23]:
for item in x:
    print(item)

leo
yvonne


In [25]:
x['leo']

'shipeng'

In [27]:
x['yvonne']

'huan'

## map(function, iterable)

In [31]:
store1 = [10,11,12,24]
store2 = [1,6,11,25]

In [45]:
cheapest = map(min, store1, store2)
list(cheapest)

[1, 6, 11, 24]

In [47]:
def half(number):
    return number/2

In [51]:
half_map = map(half, store1)

In [53]:
list(half_map)

[5.0, 5.5, 6.0, 12.0]

## lambda
 is a way to create anonymous function in Python data science, its just a way to write the function in one line 

In [63]:
fun = lambda a,b,c : a+b

In [65]:
fun(1,2,3)

3

In [74]:
# list comprehension
my_list = [i for i in range(1000) if i %2 ==0]

In [76]:
my_list

[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100,
 102,
 104,
 106,
 108,
 110,
 112,
 114,
 116,
 118,
 120,
 122,
 124,
 126,
 128,
 130,
 132,
 134,
 136,
 138,
 140,
 142,
 144,
 146,
 148,
 150,
 152,
 154,
 156,
 158,
 160,
 162,
 164,
 166,
 168,
 170,
 172,
 174,
 176,
 178,
 180,
 182,
 184,
 186,
 188,
 190,
 192,
 194,
 196,
 198,
 200,
 202,
 204,
 206,
 208,
 210,
 212,
 214,
 216,
 218,
 220,
 222,
 224,
 226,
 228,
 230,
 232,
 234,
 236,
 238,
 240,
 242,
 244,
 246,
 248,
 250,
 252,
 254,
 256,
 258,
 260,
 262,
 264,
 266,
 268,
 270,
 272,
 274,
 276,
 278,
 280,
 282,
 284,
 286,
 288,
 290,
 292,
 294,
 296,
 298,
 300,
 302,
 304,
 306,
 308,
 310,
 312,
 314,
 316,
 318,
 320,
 322,
 324,
 326,
 328,
 330,
 332,
 334,
 336,
 338,
 340,
 342,
 344,
 346,
 348,
 350,

In [78]:
lowercase = 'abc'
digits = '01'

answer = [i+j+p+q for i in lowercase for j in lowercase for p in digits for q in digits]

In [82]:
len(answer)

36

# Numpy

In [86]:
mylist = [1,2,3]

In [90]:
import numpy as np

In [92]:
x = np.array(mylist)

In [94]:
x

array([1, 2, 3])

In [102]:
m = np.array([[7,8,9], [1,2,3]])

In [104]:
m


array([[7, 8, 9],
       [1, 2, 3]])

In [107]:
m.shape

(2, 3)

In [109]:
n = np.arange(0,30, 2)

In [111]:
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [113]:
n = n.reshape(3,5)

In [115]:
n

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [117]:
o = np.linspace(0,4,9)

In [119]:
o

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [121]:
o = np.linspace(0.01, 0.2, 5)

In [123]:
o

array([0.01  , 0.0575, 0.105 , 0.1525, 0.2   ])

In [127]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [129]:
np.zeros((10000, 12))

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [133]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [135]:
x

array([1, 2, 3])

In [137]:
np.diag(x)

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [141]:
m

array([[7, 8, 9],
       [1, 2, 3]])

In [143]:
np.diag(m)

array([7, 2])

In [145]:
np.array([1,2,3]*2)

array([1, 2, 3, 1, 2, 3])

In [147]:
np.repeat([1,2,3], 2)

array([1, 1, 2, 2, 3, 3])

In [157]:
p = np.ones((2,3), int)

In [159]:
p

array([[1, 1, 1],
       [1, 1, 1]])

In [165]:
np.vstack([p, p*2])

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

In [167]:
np.hstack([p, p*3])

array([[1, 1, 1, 3, 3, 3],
       [1, 1, 1, 3, 3, 3]])

## opeations

In [171]:
p.dtype

dtype('int32')

In [193]:
w = np.array([[1,2,3], [4,'0',2]])
w

array([['1', '2', '3'],
       ['4', '0', '2']], dtype='<U11')

In [195]:
w.dtype

dtype('<U11')

In [197]:
w = w.astype('f')
w

array([[1., 2., 3.],
       [4., 0., 2.]], dtype=float32)

In [199]:
w.sum()

12.0

In [201]:
w.min()

0.0

In [203]:
w.max()

4.0

In [205]:
w.mean()

2.0

In [207]:
w.argmax()

3

In [209]:
w.argmin()

4

In [213]:
r = np.arange(36)
r

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [223]:
r.resize((6,6))

In [225]:
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [227]:
r[0,3]

3

In [229]:
r[[0,3]]

array([[ 0,  1,  2,  3,  4,  5],
       [18, 19, 20, 21, 22, 23]])

In [231]:
r[0]

array([0, 1, 2, 3, 4, 5])

In [235]:
r[1,]

array([ 6,  7,  8,  9, 10, 11])

In [245]:
r[:, 1]

array([ 1,  7, 13, 19, 25, 31])

In [249]:
r[r>31]

array([32, 33, 34, 35])

In [251]:
r[r>30] = 0

In [253]:
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30,  0,  0,  0,  0,  0]])

In [257]:
r2 = r[:2,:2]

In [259]:
r2 

array([[0, 1],
       [6, 7]])

In [261]:
r2[:] = 0

In [263]:
r2

array([[0, 0],
       [0, 0]])

In [265]:
r

array([[ 0,  0,  2,  3,  4,  5],
       [ 0,  0,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30,  0,  0,  0,  0,  0]])

In [267]:
r_copy = r.copy()

In [269]:
r_copy[:] = 10

In [271]:
r_copy

array([[10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10]])

In [273]:
r

array([[ 0,  0,  2,  3,  4,  5],
       [ 0,  0,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30,  0,  0,  0,  0,  0]])

In [281]:
test = np.random.randint(0,9, (4,3))

In [283]:
test

array([[1, 5, 1],
       [2, 5, 8],
       [8, 5, 5],
       [4, 2, 8]])

In [285]:
for i, row in enumerate(test):
    print(i)
    print(row)

0
[1 5 1]
1
[2 5 8]
2
[8 5 5]
3
[4 2 8]


In [287]:
test2 = test**2

In [289]:
test2

array([[ 1, 25,  1],
       [ 4, 25, 64],
       [64, 25, 25],
       [16,  4, 64]])

In [ ]:
for i, j in zip(test, test2):
    

In [ ]:
for i in range(len(nums)-1):
            for j in range(i, len(nums)):
                if nums[i] + nums[i] == target:
                    return [i,j]

In [293]:
p = [[2,3]]

In [295]:
print(type(p))

<class 'list'>


In [297]:
p[0]

[2, 3]

In [299]:
len(p)

1

In [367]:
num1 = [0,0,4,6,8]
num2 = [0,0,1,7,8]
num1+num2


[0, 0, 6, 4, 8, 0, 0, 1, 7, 8]

In [369]:
num1.sort()
num1

[0, 0, 4, 6, 8]

## DataFrame

In [374]:
import pandas as pd

df = pd.DataFrame([{'Name': 'Chris', 'Item Purchased': 'Sponge', 'Cost': 22.50},
                   {'Name': 'Kevyn', 'Item Purchased': 'Kitty Litter', 'Cost': 2.50},
                   {'Name': 'Filip', 'Item Purchased': 'Spoon', 'Cost': 5.00}],
                  index=['Store 1', 'Store 1', 'Store 2'])
df

Name Item Purchased  Cost
Store 1  Chris         Sponge  22.5
Store 1  Kevyn   Kitty Litter   2.5
Store 2  Filip          Spoon   5.0

In [382]:
df1 = pd.DataFrame({'A': [1,2,3], 'B': [4,5,6]})

In [384]:
df1

A  B
0  1  4
1  2  5
2  3  6

In [386]:
df['Date'] = ['December 1', 'January 1', 'mid-May']
df

Name Item Purchased  Cost        Date
Store 1  Chris         Sponge  22.5  December 1
Store 1  Kevyn   Kitty Litter   2.5   January 1
Store 2  Filip          Spoon   5.0     mid-May

In [388]:
df['Delivered'] = True
df

Name Item Purchased  Cost        Date  Delivered
Store 1  Chris         Sponge  22.5  December 1       True
Store 1  Kevyn   Kitty Litter   2.5   January 1       True
Store 2  Filip          Spoon   5.0     mid-May       True

In [390]:
df['Feedback'] = ['Positive', None, 'Negative']
df

Name Item Purchased  Cost        Date  Delivered  Feedback
Store 1  Chris         Sponge  22.5  December 1       True  Positive
Store 1  Kevyn   Kitty Litter   2.5   January 1       True      None
Store 2  Filip          Spoon   5.0     mid-May       True  Negative

In [392]:
adf = df.reset_index()
adf

index   Name Item Purchased  Cost        Date  Delivered  Feedback
0  Store 1  Chris         Sponge  22.5  December 1       True  Positive
1  Store 1  Kevyn   Kitty Litter   2.5   January 1       True      None
2  Store 2  Filip          Spoon   5.0     mid-May       True  Negative

In [394]:
t = pd.Series({0: 'December 1', 2: 'mid-May'})
t

0    December 1
2       mid-May
dtype: object